services:
  oauth2-postgres:
    image: postgres:16.3-alpine
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sso
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
